---

kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/xhgui-agent

steps:
- name: test
  pull: default
  image: golang
  commands:
  - go test -v -cover ./...