version: "3"
services:
  web:
    image: bearstech/nginx
    depends_on:
      - php
    ports:
      - 8000:8000
    volumes:
      - ./contribs/client/nginx.conf:/etc/nginx/sites-enabled/default
      - ./contribs/client/web:/var/www/web

  php:
    image: php-with-xhgui-agent
    user: www-data
    environment:
      XHGUI_UPLOAD_URI: http://agent:8002
      XHGUI_PROFILING: "1"
      XHGUI_PROFILING_RATIO: "100"
    depends_on:
      - agent
    volumes:
      - ./contribs/client/web:/var/www/web

  agent:
    image: xhgui-agent
    environment:
      LISTEN: 0.0.0.0:8002
      MONGODB_URL: mongodb://xhprof:example@mongodb/xhprof?authSource=admin
    depends_on:
      - mongodb
    ports:
      - 8002:8002

  xhgui:
    image: xhgui-nginx
    ports:
      - 8001:8000
    depends_on:
      - xhgui-php

  xhgui-php:
    image: xhgui-php
    depends_on:
      - mongodb
    environment:
      MONGO_PASSWORD: example
      MONGO_HOST: mongodb
    volumes:
      - ./data/cache:/opt/xhgui/cache

  mongodb:
    image: mongo:3.6
    environment:
      MONGO_INITDB_DATABASE: xhprof
      MONGO_INITDB_ROOT_USERNAME: xhprof
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
